### ISSUE TITLE
Massive scrolling performance improvements

### ISSUE THREAD

**Issue by fxbrain** [caddyserver/caddyserver.com#1]
Hi.
Due to the way your backgrounds are defined (frontpage.css) the whole page will get repainted on every scroll. It would be much better to:
- fix the background  making it a ::before pseudo-element. 
- promote the nav bar to own layer
```
.bg1::before {
	background-image: url('/resources/images/atomicthing2.jpg');
}

.bg2::before {
	background-image: url('/resources/images/crystalpines.jpg');
}

.bg3::before {
	background-image: url('/resources/images/allthatglitters.jpg');
}

.bg4::before {
	background-image: url('/resources/images/circuitboard.jpg');
}

nav {
    background: rgba(0, 33, 50, .9);
    box-shadow: none;
    height: 65px;
    overflow: hidden;
    /* will-change: transform; */
    transform: translateZ(0); /* atm better than will-change. has better browser support */
}
```
**Timeline without improvements:** 
![screenshot 2015-06-22 at 12 51 39 am](https://cloud.githubusercontent.com/assets/3898841/8273718/e178bb86-1878-11e5-9a3b-95ca3f008104.png)

**Timeline after improvements:**
![screenshot 2015-06-22 at 1 00 34 am](https://cloud.githubusercontent.com/assets/3898841/8273737/28274dbc-187a-11e5-9068-8de59056db41.png)

**Comment by mholt** [comment]
I didn't know about this trick! The performance gains look really tasty - but how do I get the background images to stay visible? When I apply ::before to the four bg classes, they disappear and the background of those images is white.

![bg1::before](https://cloud.githubusercontent.com/assets/1128849/8274658/cdd8b25a-1852-11e5-8eda-5ee1cee5aac6.png)

**Comment by fxbrain** [comment]
Ouch! Sorry my mistake. No wonder performance is rising ;). I am on it at the moment. Maybe it would be better to organize the different backgrounds in layers. Gosh. I love parallax :(

Anyways. The navbar fix is already, although minor, an improvement.

Rest will follow.

Chears

Stefan

**Comment by mholt** [comment]
Okay, no problem! Let me know what you discover. :smile:

**Comment by mholt** [comment]
@fxbrain Any luck with this? You've whet my appetite already...
