### ISSUE TITLE
getcaddy.com / installer script on site

### ISSUE THREAD

**Issue by coolaj86** [caddyserver/caddyserver.com#16]
Is there anything I can do to help get `https://getcaddy.com` on https://caddyserver.com/download?

I'm imagining an interface where it starts as simple as `curl 'https://getcaddy.com' | bash` as you check the boxes the  command changes `curl 'https://getcaddy.com' | bash -s git,search`.

With a little direction I can do some minor updates to the javascript on the page.

**Comment by mholt** [comment]
:+1: I like this idea. I just got that domain accepted into LE's beta program.

I'm in the early stages of redesigning the website right now, and I will make sure that there's a place for this on the new download page. In the meantime, you're welcome to work on the JS for it with what we've got -- https://caddyserver.com/resources/js/download.js - see featureList function and updateDownloadLinks function.

With the new design, I think we'll also have a new plugin picker that scales a little better... just FYI.

**Comment by coolaj86** [comment]
https://github.com/caddyserver/caddyserver.com/pull/18
https://github.com/caddyserver/caddyserver.com/pull/19

**Comment by theel0ja** [comment]
Still not there...

**Comment by mholt** [comment]
This is still open. I'm building a new site.

**Comment by mholt** [comment]
This is implemented on the new site, currently under construction.
