### ISSUE TITLE
Use CSP on redesign

### ISSUE THREAD

**Issue by coolaj86** [caddyserver/caddyserver.com#20]
Here's a decent default CSP tag you can put in `<head></head>` on the redesign.

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' https://caddyserver.com; style-src 'self' https://caddyserver.com; img-src 'self' https:// data: blob:; font-src: 'self' https:// data: blob:; media-src: 'self' https:// data: blob:; connect-src 'self'; child-src 'none'; object-src 'none'; upgrade-insecure-requests;"> 
```

Then if you need to add something from a cdn you can add it to the list.

 Example:

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' https://xyz.googlecdn.com; style-src 'self' https://xyz.googlecdn.com https://abc.maxcdn.com;"> 
```

It makes avoiding inline styles a lot easier (which is a problem on the current site) and helps you find any places where you left stray external links (not that you have any).

**Comment by mholt** [comment]
I've just implemented CSP and other security-related headers. Thanks!
