### ISSUE TITLE
site1, site2 config

### ISSUE THREAD

**Issue by jungle-boogie** [caddyserver/caddyserver.com#23]
Hello,

In the readme for caddy, there's discussion about running multiple sites with a single caddy file:
https://github.com/mholt/caddy/blob/master/README.md

In the example, it has this: `sub.site2.com` 
Question: Are we assuming the user knows they will need to setup an a record for that subdomain to resolve, or is there something caddy is actually doing make it not necessary for the a record?

Thanks!

**Comment by mholt** [comment]
Caddy is just a web server; it doesn't change domain configurations. As usual, the user must point the domain to the machine where the site is.

**Comment by jungle-boogie** [comment]
Yes, that I understand.

Should the documentation state that or are you assuming the user will already know that?

**Comment by mholt** [comment]
The user should already know that.
