### ISSUE TITLE
Make sudo usage smarter

### ISSUE THREAD

**Issue by NuSkooler** [caddyserver/caddyserver.com#40]
**Problem**:
`sudo` not present in various environments. For example, a FreeBSD Jail.

**Suggested**:
`sudo` in the script should be optional / only used when not already running as root.

**Comment by mholt** [comment]
Great -- do you have any idea on the right way to do that? I've never done that before :smile:

**Comment by NuSkooler** [comment]
@mholt: I'm not sure the best way, but I'll do a little experimentation and get back to you!

**Comment by NuSkooler** [comment]
OK, this works on my FreeBSD 10.1 and 10.2 systems:

```
SUDO_PREFIX=""
if [[ $EUID -ne 0 ]]; then
    SUDO_PREFIX="sudo"
fi

# ...
$SUDO_PREFIX something that requires sudo
```

(e.g. replace all `sudo` with `$SUDO_PREFIX`)

**Comment by mholt** [comment]
Alright, I'll make it so in a minute. Thanks!

**Comment by mholt** [comment]
@NuSkooler I've made the change. Feel free to double-check it works.
