### ISSUE TITLE
Plugin names not rendering at all in Win10/Chrome

### ISSUE THREAD

**Issue by MSF-Jarvis** [caddyserver/caddyserver.com#59]
![Henrique messes up](http://i.imgur.com/0uTvHPI.png)

I can confirm that it doesn't happen over mobile since I've downloaded the builds for my local machine and phone itself over Android M/Chromium without seeing this.

**Comment by MSF-Jarvis** [comment]
@hacdias, thoughts on this?

**Comment by hacdias** [comment]
Hello @MSF-Jarvis,

I can't open the site right now (```ERR_CONNECTION_REFUSED```) but I was in the website this morning and it showed everything correctly, but not with that design. :O I guess we have to way till the site is back online to check it out.

**Comment by MSF-Jarvis** [comment]
*wait

**Comment by MSF-Jarvis** [comment]
Ideal facepalm notwithstanding, yes, until the site is online we can't do
anything, unless someone shows you that `hugo server -w` is a thing ;)

**Comment by mholt** [comment]
Did you clear your cache?

**Comment by MSF-Jarvis** [comment]
I reinstalled the web browser a couple of times to no avail

**Comment by mholt** [comment]
I think it's a browser cache issue still. The site renders fine here.

**Comment by MSF-Jarvis** [comment]
Hmm, I'll try to wipe off that school PC then and see how it goes after
they set it up from scratch again.

**Comment by mholt** [comment]
Or just open the dev tools and check "Disable cache" :P

**Comment by MSF-Jarvis** [comment]
Where's the fun in that?

**Comment by hacdias** [comment]
Everything works here.
