### ISSUE TITLE
Caddyfile.md unspecific about environment variable cross-platform portability

### ISSUE THREAD

**Issue by MarkDBlackwell** [caddyserver/caddyserver.com#61]
CASE

Webpage `Caddyfile.md` [says](https://github.com/caddyserver/caddyserver.com/blame/81ef84ca3470869adefee306311d81691cdf7ac1/content/docs/caddyfile.md#L78):

> Power users may wish to use environment variables...you can use either Unix or Windows variable formats:
```
localhost:{$PORT}
root {%SITE_ROOT%}
```

First time reader question:

1. Is this merely a loosened syntax? So...will user codebases including either one of these usages still be portable (across Unix and Windows)? (Or is user-codebase portability perhaps irrelevant for Caddy somehow?) Or
1. Does each usage work only when running on its own kind of operating system?

If the latter, might somewhat-unexpected behavior in general occur when each usage is run on the wrong kind of operating system? due to this feature lacking [fail fast](https://en.wikipedia.org/w/index.php?title=Fail-fast&oldid=726094723) behavior (hypothetically)?

For example: on Unix systems, will `root {%SITE_ROOT%}` work (after `export SITE_ROOT=http://example.org`)?

PLAN

The documentation webpage should say whether (or not) usage of each environment-variable format is allowed (without failing fast) when running on another format's operating system (currently).

If allowed, it should say whether (or not) each format (in user code) works fully (i.e., portably) in the other kind of operating system (currently).

For this feature, if Caddy lacks both portability and fail fast behavior (currently), then the documentation webpage should warn that unexpected behavior might occur if this restriction (to its own kind of operating system) isn't followed.

[Caddyfile/parse.go](https://github.com/mholt/caddy/blob/4b3c53257353f4df8b3a0aeb3241cbc3d7d71de3/caddyfile/parse.go#L373) and numerous tests in [caddyfile/parse_test.go](https://github.com/mholt/caddy/blob/4b3c53257353f4df8b3a0aeb3241cbc3d7d71de3/caddyfile/parse_test.go#L323) apparently indicate Caddy includes this portability. However, for novice Caddy users, the documentation webpage IMO should include the above information.

**Comment by mholt** [comment]
Either syntax works on any platform. I figured that would be so easy that we didn't need to mention it, since it's not something the user needs to think about.

**Comment by MarkDBlackwell** [comment]
This behavior seems unfamiliar—which would generate uncertainty, for some—yet obviously it's good.

Clarifying this IMO would lessen some people's time spent investigating the portability issue.
