### ISSUE TITLE
"Client.Timeout exceeded while awaiting headers"

### ISSUE THREAD

**Issue by k0nsl** [caddyserver/caddyserver.com#79]
This is from a server running version 0.9.2 of Caddyserver:
```
k0nsl@abletest:~$ 2016/09/24 03:36:02 get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
I tried with the firewall on and off and it doesn't make any difference. The `Caddyfile` would be superfluous to post as I know everything in there is absolute correct.

The operating system is Debian 8 on kernel `3.16.0-4-amd64`. Any ideas? I'm stuck.

**Comment by mholt** [comment]
Thanks for your question. :) I've never seen this myself but heard of it with others. It seems your network has very high latency between there and the Let's Encrypt servers. Try using the `-catimeout` flag and set it to a higher value (like 30s or 1m).

FYI this is the repo for the website, not Caddy itself. ;) If you have more questions about using Caddy, feel free to post on our forums: https://forum.caddyserver.com
